// AUTO-GENERATED by scripts/generate-ast-types.ts — do not edit.
// Source: src/node-types.json (emitted by tree-sitter generate).

export interface Position {
  /** Zero-based row. */
  row: number;
  /** Zero-based column, in UTF-16 code units. */
  column: number;
}

export interface BaseNode<TType extends string, TChild = never> {
  type: TType;
  startPosition: Position;
  endPosition: Position;
  startIndex: number;
  endIndex: number;
  text: string;
  isMissing: boolean;
  hasError: boolean;
  children: TChild[];
}

export type DocumentNode = BaseNode<'document', HtmlDoctypeNode | HtmlElementNode | HtmlEntityNode | HtmlErroneousEndTagNode | HtmlRawElementNode | HtmlScriptElementNode | HtmlStyleElementNode | MustacheCommentNode | MustacheInterpolationNode | MustacheInvertedSectionNode | MustachePartialNode | MustacheSectionNode | MustacheTripleNode | TextNode>;
export type HtmlAttributeNode = BaseNode<'html_attribute', HtmlAttributeNameNode | HtmlAttributeValueNode | HtmlQuotedAttributeValueNode | MustacheInterpolationNode>;
export type HtmlAttributeNameNode = BaseNode<'html_attribute_name', never>;
export type HtmlAttributeValueNode = BaseNode<'html_attribute_value', never>;
export type HtmlCommentNode = BaseNode<'html_comment', never>;
export type HtmlDoctypeNode = BaseNode<'html_doctype', never>;
export type HtmlElementNode = BaseNode<'html_element', HtmlDoctypeNode | HtmlElementNode | HtmlEndTagNode | HtmlEntityNode | HtmlErroneousEndTagNode | HtmlForcedEndTagNode | HtmlRawElementNode | HtmlScriptElementNode | HtmlSelfClosingTagNode | HtmlStartTagNode | HtmlStyleElementNode | MustacheCommentNode | MustacheInterpolationNode | MustacheInvertedSectionNode | MustachePartialNode | MustacheSectionNode | MustacheTripleNode | TextNode>;
export type HtmlEndTagNode = BaseNode<'html_end_tag', HtmlTagNameNode>;
export type HtmlEntityNode = BaseNode<'html_entity', never>;
export type HtmlErroneousEndTagNode = BaseNode<'html_erroneous_end_tag', HtmlErroneousEndTagNameNode>;
export type HtmlErroneousEndTagNameNode = BaseNode<'html_erroneous_end_tag_name', never>;
export type HtmlForcedEndTagNode = BaseNode<'html_forced_end_tag', never>;
export type HtmlQuotedAttributeValueNode = BaseNode<'html_quoted_attribute_value', HtmlAttributeValueNode | MustacheCommentNode | MustacheInterpolationNode | MustacheInvertedSectionNode | MustachePartialNode | MustacheSectionNode | MustacheTripleNode>;
export type HtmlRawElementNode = BaseNode<'html_raw_element', HtmlEndTagNode | HtmlRawTextNode | HtmlStartTagNode>;
export type HtmlRawTextNode = BaseNode<'html_raw_text', never>;
export type HtmlScriptElementNode = BaseNode<'html_script_element', HtmlEndTagNode | HtmlRawTextNode | HtmlStartTagNode>;
export type HtmlSelfClosingTagNode = BaseNode<'html_self_closing_tag', HtmlAttributeNode | HtmlTagNameNode | MustacheAttributeNode | MustacheInterpolationNode | MustacheTripleNode>;
export type HtmlStartTagNode = BaseNode<'html_start_tag', HtmlAttributeNode | HtmlTagNameNode | MustacheAttributeNode | MustacheInterpolationNode | MustacheTripleNode>;
export type HtmlStyleElementNode = BaseNode<'html_style_element', HtmlEndTagNode | HtmlRawTextNode | HtmlStartTagNode>;
export type HtmlTagNameNode = BaseNode<'html_tag_name', never>;
export type MustacheAttributeNode = BaseNode<'mustache_attribute', MustacheInvertedSectionNode | MustacheSectionNode>;
export type MustacheCommentNode = BaseNode<'mustache_comment', MustacheCommentContentNode>;
export type MustacheCommentContentNode = BaseNode<'mustache_comment_content', never>;
export type MustacheErroneousInvertedSectionEndNode = BaseNode<'mustache_erroneous_inverted_section_end', MustacheErroneousTagNameNode>;
export type MustacheErroneousSectionEndNode = BaseNode<'mustache_erroneous_section_end', MustacheErroneousTagNameNode>;
export type MustacheErroneousTagNameNode = BaseNode<'mustache_erroneous_tag_name', never>;
export type MustacheIdentifierNode = BaseNode<'mustache_identifier', never>;
export type MustacheInterpolationNode = BaseNode<'mustache_interpolation', MustacheIdentifierNode | MustachePathExpressionNode>;
export type MustacheInvertedSectionNode = BaseNode<'mustache_inverted_section', HtmlAttributeNode | HtmlDoctypeNode | HtmlElementNode | HtmlEntityNode | HtmlErroneousEndTagNode | HtmlRawElementNode | HtmlScriptElementNode | HtmlStyleElementNode | MustacheAttributeNode | MustacheCommentNode | MustacheErroneousInvertedSectionEndNode | MustacheInterpolationNode | MustacheInvertedSectionBeginNode | MustacheInvertedSectionEndNode | MustacheInvertedSectionNode | MustachePartialNode | MustacheSectionNode | MustacheTripleNode | TextNode>;
export type MustacheInvertedSectionBeginNode = BaseNode<'mustache_inverted_section_begin', MustacheTagNameNode>;
export type MustacheInvertedSectionEndNode = BaseNode<'mustache_inverted_section_end', MustacheTagNameNode>;
export type MustachePartialNode = BaseNode<'mustache_partial', MustachePartialContentNode>;
export type MustachePartialContentNode = BaseNode<'mustache_partial_content', never>;
export type MustachePathExpressionNode = BaseNode<'mustache_path_expression', MustacheIdentifierNode>;
export type MustacheSectionNode = BaseNode<'mustache_section', HtmlAttributeNode | HtmlDoctypeNode | HtmlElementNode | HtmlEntityNode | HtmlErroneousEndTagNode | HtmlRawElementNode | HtmlScriptElementNode | HtmlStyleElementNode | MustacheAttributeNode | MustacheCommentNode | MustacheErroneousSectionEndNode | MustacheInterpolationNode | MustacheInvertedSectionNode | MustachePartialNode | MustacheSectionBeginNode | MustacheSectionEndNode | MustacheSectionNode | MustacheTripleNode | TextNode>;
export type MustacheSectionBeginNode = BaseNode<'mustache_section_begin', MustacheTagNameNode>;
export type MustacheSectionEndNode = BaseNode<'mustache_section_end', MustacheTagNameNode>;
export type MustacheTagNameNode = BaseNode<'mustache_tag_name', never>;
export type MustacheTripleNode = BaseNode<'mustache_triple', MustacheIdentifierNode | MustachePathExpressionNode>;
export type TextNode = BaseNode<'text', never>;

/** Inserted by tree-sitter when input could not be parsed. May contain any subtree. */
export type ErrorNode = BaseNode<'ERROR', SyntaxNode>;

export type SyntaxNode =
  | DocumentNode
  | HtmlAttributeNode
  | HtmlAttributeNameNode
  | HtmlAttributeValueNode
  | HtmlCommentNode
  | HtmlDoctypeNode
  | HtmlElementNode
  | HtmlEndTagNode
  | HtmlEntityNode
  | HtmlErroneousEndTagNode
  | HtmlErroneousEndTagNameNode
  | HtmlForcedEndTagNode
  | HtmlQuotedAttributeValueNode
  | HtmlRawElementNode
  | HtmlRawTextNode
  | HtmlScriptElementNode
  | HtmlSelfClosingTagNode
  | HtmlStartTagNode
  | HtmlStyleElementNode
  | HtmlTagNameNode
  | MustacheAttributeNode
  | MustacheCommentNode
  | MustacheCommentContentNode
  | MustacheErroneousInvertedSectionEndNode
  | MustacheErroneousSectionEndNode
  | MustacheErroneousTagNameNode
  | MustacheIdentifierNode
  | MustacheInterpolationNode
  | MustacheInvertedSectionNode
  | MustacheInvertedSectionBeginNode
  | MustacheInvertedSectionEndNode
  | MustachePartialNode
  | MustachePartialContentNode
  | MustachePathExpressionNode
  | MustacheSectionNode
  | MustacheSectionBeginNode
  | MustacheSectionEndNode
  | MustacheTagNameNode
  | MustacheTripleNode
  | TextNode
  | ErrorNode;

/** String-literal union of every named node type, including `ERROR`. */
export type NodeType = SyntaxNode['type'];
