/**
 * Generate `js/parser/nodeTypes.generated.ts` from `src/node-types.json`.
 *
 * tree-sitter emits `node-types.json` alongside `parser.c` whenever
 * `tree-sitter generate` runs. We use it as the source of truth for the
 * discriminated AST union exposed by the `./parser` entry, so the types stay
 * in sync with the grammar without hand-maintenance.
 *
 * Hidden rules (named, but starting with `_`) are filtered out: tree-sitter
 * inlines them at parse time, so they never appear in the tree consumers see.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';

interface ChildTypeRef {
  type: string;
  named: boolean;
}

interface NodeTypeEntry {
  type: string;
  named: boolean;
  root?: boolean;
  fields?: Record<string, { multiple: boolean; required: boolean; types: ChildTypeRef[] }>;
  children?: { multiple: boolean; required: boolean; types: ChildTypeRef[] };
  subtypes?: ChildTypeRef[];
}

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(__filename), '..');
const SOURCE = path.join(REPO_ROOT, 'src', 'node-types.json');
const OUT = path.join(REPO_ROOT, 'js', 'parser', 'nodeTypes.generated.ts');

const raw = readFileSync(SOURCE, 'utf8');
const entries: NodeTypeEntry[] = JSON.parse(raw);

// Visible named types — `_`-prefixed ones are hidden by tree-sitter and never
// appear in the tree at runtime.
const visible = entries.filter((e) => e.named && !e.type.startsWith('_'));
visible.sort((a, b) => a.type.localeCompare(b.type));

function pascalCase(s: string): string {
  return s
    .split(/[_-]/)
    .map((part) => part.length === 0 ? '' : part[0].toUpperCase() + part.slice(1))
    .join('');
}

function interfaceNameFor(typeName: string): string {
  return `${pascalCase(typeName)}Node`;
}

function childrenUnion(entry: NodeTypeEntry): string {
  const types = entry.children?.types ?? [];
  const named = types.filter((t) => t.named && !t.type.startsWith('_'));
  if (named.length === 0) return 'never';
  const unique = Array.from(new Set(named.map((t) => interfaceNameFor(t.type)))).sort();
  return unique.join(' | ');
}

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/generate-ast-types.ts — do not edit.');
lines.push('// Source: src/node-types.json (emitted by tree-sitter generate).');
lines.push('');
lines.push('export interface Position {');
lines.push('  /** Zero-based row. */');
lines.push('  row: number;');
lines.push('  /** Zero-based column, in UTF-16 code units. */');
lines.push('  column: number;');
lines.push('}');
lines.push('');
lines.push('export interface BaseNode<TType extends string, TChild = never> {');
lines.push('  type: TType;');
lines.push('  startPosition: Position;');
lines.push('  endPosition: Position;');
lines.push('  startIndex: number;');
lines.push('  endIndex: number;');
lines.push('  text: string;');
lines.push('  isMissing: boolean;');
lines.push('  hasError: boolean;');
lines.push('  children: TChild[];');
lines.push('}');
lines.push('');

for (const entry of visible) {
  const iface = interfaceNameFor(entry.type);
  const childUnion = childrenUnion(entry);
  lines.push(`export type ${iface} = BaseNode<'${entry.type}', ${childUnion}>;`);
}

// Synthetic ERROR node — not in node-types.json but tree-sitter emits it for
// unrecoverable parse failures. Allow any visible node as a child to be
// permissive.
lines.push('');
lines.push("/** Inserted by tree-sitter when input could not be parsed. May contain any subtree. */");
lines.push(`export type ErrorNode = BaseNode<'ERROR', SyntaxNode>;`);
lines.push('');

const unionMembers = visible.map((e) => interfaceNameFor(e.type)).concat(['ErrorNode']);
lines.push(`export type SyntaxNode =`);
lines.push(unionMembers.map((m) => `  | ${m}`).join('\n') + ';');
lines.push('');

lines.push('/** String-literal union of every named node type, including `ERROR`. */');
lines.push(`export type NodeType = SyntaxNode['type'];`);
lines.push('');

writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`Wrote ${OUT} (${visible.length} named types + ERROR)`);
