name: LSP

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 12
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build WASM
        run: pnpm build
      - name: Build LSP
        run: pnpm run build
        working-directory: lsp
      - name: Run server tests
        run: pnpm run test
        working-directory: lsp
      - name: Lint
        run: pnpm run lint
        working-directory: lsp
